# Generated by Django 5.1.2 on 2024-11-12 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0002_tarefa_usuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tarefa',
            options={'ordering': ['-id']},
        ),
    ]
